name: rhkr8521 - CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: docker image build
        run: sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/iccas_question .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker Hub push
        run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/iccas_question

  run-docker-image-on-mapping-server:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: docker pull
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/iccas_question

      - name: stop running container
        run: |
          CONTAINER_ID=$(sudo docker ps -q --filter "name=iccas_backend")
          if [ ! -z "$CONTAINER_ID" ]; then
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -S docker stop $CONTAINER_ID
          fi

      - name: docker run new container
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -S docker run --name iccas_backend --rm -d \
          -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/iccas_question

      - name: delete old docker images
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -S docker system prune -f
